// DO NOT EDIT THIS FILE
#pragma once

#include <vector>

#include "Node.h"

int findMissingNumber(const std::vector<int>& vec);

int findMaxOfVector(const std::vector<int>& vec);

std::pair<int, int> findTwoSumPair(const std::vector<int>& vec, int targetSum);

Node<int>* add(Node<int>* l1, Node<int>* l2);