// DO NOT EDIT THIS FILE
#include "util.h"

Node<int>* makeList(int num) {
  Node<int>* head = nullptr;
  Node<int>* tail = nullptr;
  do {
    int digit = num % 10;
    num = num / 10;

    Node<int>* tmp = new Node<int>();
    tmp->value = digit;
    tmp->next = nullptr;

    if (head == nullptr) {
      // if this is the first digit, keep track of head
      head = tmp;
      tail = tmp;
    } else {
      // else link it into the list
      tail->next = tmp;
      tail = tail->next;
    }
  } while (num != 0);
  return head;
}

void freeList(Node<int>* head) {
  while (head != nullptr) {
    Node<int>* tmp = head->next;
    delete head;
    head = tmp;
  }
}
